language: php

sudo: false

php:
    - '7.0'

install:
    - composer install

cache:
  directories:
    - ${HOME}/.composer/cache

script:
    - phpunit --coverage-clover=coverage.xml


after_success:
    - bash <(curl -s https://codecov.io/bash)

    # ssh key prepare
    - mv app/integration/deploy.key.gpg .
    - gpg --yes --batch --passphrase=${DEPLOY_KEY_PASSWORD} deploy.key.gpg
    - chmod 600 deploy.key
    - mv deploy.key ~/.ssh
    - ssh-keyscan ${DEPLOY_SSH_HOST} >> ~/.ssh/known_hosts
    - echo "Host deploy" >> ~/.ssh/config
    - echo "  HostName ${DEPLOY_SSH_HOST}" >> ~/.ssh/config
    - echo "  User ${DEPLOY_SSH_USER}" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/deploy.key" >> ~/.ssh/config

    # Deploying with git
    - git config --global push.default simple
    - git remote add deploy ssh://deploy/~/git/rockparade
    - git fetch --unshallow || true
    - git fetch origin "+refs/heads/*:refs/remotes/origin/*"
    - git push deploy master

    # Installing dependencies
    - ssh deploy /home/deployer/composer.phar install -d /home/deployer/git/rockparade

    # Clear Symfony cache
    - ssh deploy /home/deployer/git/rockparade/bin/console ca:cl -e prod

notifications:
    slack: rockparade:IxVBagXvchm7GgEPukl71YTu
