parameters:
#    parameter_name: value

services:

    # Loggers
    rockparade.api_logger:
        class: Monolog\Logger
        arguments: ['api']
        calls:
            - [pushHandler, ['@rockparade.api_handler']]
    rockparade.api_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%kernel.logs_dir%/api.log']
        calls:
            - [setFormatter, ['@rockparade.log_formatter']]
    rockparade.log_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%%\n"
    rockparade.exception_logger:
        class: Monolog\Logger
        arguments: ['api']
        calls:
            - [pushHandler, ['@rockparade.exception_logger_handler']]
    rockparade.exception_logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ '%kernel.logs_dir%/exceptions.log']
        calls:
            - [setFormatter, ['@rockparade.log_formatter']]

    # Repositories
    rockparade.user_repository:
        class: AppBundle\Entity\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\User']
    rockparade.band_repository:
        class: AppBundle\Entity\Repository\BandRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Band']
    rockparade.band_member_repository:
        class: AppBundle\Entity\Repository\BandMemberRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\BandMember']
    rockparade.role_repository:
        class: AppBundle\Entity\Repository\RoleRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Role']
    rockparade.event_repository:
        class: AppBundle\Entity\Repository\EventRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Event']
    rockparade.image_repository:
        class: AppBundle\Entity\Repository\ImageRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Image']
    rockparade.link_repository:
        class: AppBundle\Entity\Repository\LinkRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Link']

    # Services
    rockparade.band:
        class: AppBundle\Service\BandService
        arguments: ['@rockparade.band_repository', '@rockparade.band_member_repository', '@rockparade.user_repository']
    rockparade.user:
        class: AppBundle\Service\UserService
        arguments: ['@rockparade.vkontakte', '@rockparade.user_repository']
    rockparade.http_response_factory:
        class: AppBundle\Service\HttpResponseFactory
        arguments: ['@jms_serializer']
    rockparade.vkontakte:
        class: AppBundle\Service\Vkontakte\VkontakteClient
        arguments: ['%vkontakte.version%', '%vkontakte.client_id%', '%vkontakte.client_secret%']
    rockparade.token_authenticator:
        class: AppBundle\Service\Security\TokenAuthenticator
        arguments: ['@rockparade.user_repository']
    rockparade.image_extension_checker:
        class: AppBundle\Service\File\ImageExtensionChecker
    rockparade.file_service:
        class: AppBundle\Service\File\FileService
        arguments: ['%kernel.root_dir%', '@rockparade.image_repository', '@rockparade.image_extension_checker']
    rockparade.api_response_factory:
        class: AppBundle\Response\ApiResponseFactory
        arguments: ['%kernel.root_dir%']
    rockparade.event:
        class: AppBundle\Service\Event\EventService
        arguments: ['@rockparade.event_repository', '@rockparade.link_repository', '@router', '@rockparade.file_service']
    rockparade.extractor:
        class: AppBundle\Service\Extractor\Extractor
        arguments: ['@router']
        public: false

    # Event listeners
    rockparade.event_listener.exception:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['%kernel.environment%', '%admin_email%', '@rockparade.exception_logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    rockparade.event_listener.controller:
        class: AppBundle\EventListener\ControllerListener
        arguments: ['@security.token_storage', '@rockparade.api_logger', '%kernel.environment%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: beforeController }
    rockparade.event_listener.serializer:
        class: AppBundle\EventListener\SerializerListener
        arguments: ['@rockparade.extractor']
        scope: request
        tags:
            - { name: jms_serializer.subscribing_handler }
